name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装编译工具
      run: sudo apt update && sudo apt install -y g++

    - name: 编译 C++ 代码
      run: g++ -o my_program main.cpp

    - name: 运行程序（可选）
      run: ./my_program
